name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      matrix: 
        go: [1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.10, 1.11, 1.01, 1.08, 1.09]
        flag: [abc, xyz, ctr, sds, ytu, iuf, fre, hit, jgy, yir, uyt, iyt, poi, lit, ase, tyv, ajt, vuy]

    steps:

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: |
        hostname
        date
        go run main.go -g=${{ matrix.flag }}
        # sleep 600
